CREATE TABLE IF NOT EXISTS document_yjs_states (
  document_id VARCHAR(36) NOT NULL PRIMARY KEY,
  state LONGBLOB NOT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
